// <auto-generated />
using ElectricityConsumption.Server.Infrastructure.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ElectricityConsumption.Server.Infrastructure.Migrations
{
    [DbContext(typeof(MeterUsageContext))]
    partial class MeterUsageContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.4");

            modelBuilder.Entity("ElectricityConsumption.Server.Core.Protos.MeterReading", b =>
                {
                    b.Property<string>("Time")
                        .HasColumnType("TEXT");

                    b.Property<double>("MeterUsage")
                        .HasColumnType("REAL");

                    b.HasKey("Time");

                    b.ToTable("MeterReadings");
                });
#pragma warning restore 612, 618
        }
    }
}
