version: "3.9"
services:
    server:
        container_name: electricity_consumption_server
        build:
          context: ./ElectricityConsumption.Server
          dockerfile: ./ElectricityConsumption.Server/Dockerfile
        environment:
          - ASPNETCORE_ENVIRONMENT=Development         
        ports:
          - "8001:80"
    api:
        container_name: electricity_consumption_api
        build:
          context: ./ElectricityConsumption.API
          dockerfile: ./ElectricityConsumption.API/Dockerfile
        environment:
          - ASPNETCORE_ENVIRONMENT=Development
          - SERVER_HOST=http://host.docker.internal:8001         
        ports:
          - "8002:80"
        depends_on:
          - server
    web:
        container_name: electricity_consumption_web
        build:
          context: ./ElectricityConsumption.Web
          dockerfile: ./Dockerfile
        ports:
          - "8000:80"    
        depends_on:
          - api                          